function makeProducts () {

    const productsToMake = [
        {product: "baseball cap", description: 'A Black one size fits all baseball cap', size: 'one size fits all', color: 'black', price: 25.00,},
        {product: "baseball cap", description: 'A Orange one size fits all baseball cap', size: 'one size fits all', color: 'orange', price: 25.00},
        {product: "baseball cap", description: 'A Tan one size fits all baseball cap', size: 'one size fits all', color: 'tan', price: 25.00},
        {product: "stocking cap", description: 'A Black one size fits all stocking cap', size: 'one size fits all', color: 'black', price: 20.00},
        {product: "stocking cap", description: 'A Grey one size fits all stocking cap', size: 'one size fits all', color: 'grey', price: 20.00},
        {product: "stocking cap", description: 'A Red one size fits all stocking cap', size: 'one size fits all', color: 'red', price: 20.00},
        {product: "crew neck", description: 'A simple black crewneck with Embroidered Logo on the front', size: 'small', color: 'black', price: 39.99},
        {product: "crew neck", description: 'A simple black crewneck with Embroidered Logo on the front', size: 'medium', color: 'black', price: 39.99},
        {product: "crew neck", description: 'A simple black crewneck with Embroidered Logo on the front', size: 'large', color: 'black', price: 39.99},
        {product: "crew neck", description: 'A simple black crewneck with Embroidered Logo on the front', size: 'x large', color: 'black', price: 39.99},
        {product: "crew neck", description: 'A simple black crewneck with Embroidered Logo on the front', size: 'xx large', color: 'black', price: 39.99},
        {product: "crew neck", description: 'A simple black crewneck with Embroidered Logo on the front', size: 'xxx large', color: 'black', price: 39.99},
        {product: "crew neck", description: 'A simple blue crewneck with Embroidered Logo on the front', size: 'small', color: 'blue', price: 39.99},
        {product: "crew neck", description: 'A simple blue crewneck with Embroidered Logo on the front', size: 'medium', color: 'blue', price: 39.99},
        {product: "crew neck", description: 'A simple blue crewneck with Embroidered Logo on the front', size: 'large', color: 'blue', price: 39.99},
        {product: "crew neck", description: 'A simple blue crewneck with Embroidered Logo on the front', size: 'x large', color: 'blue', price: 39.99},
        {product: "crew neck", description: 'A simple blue crewneck with Embroidered Logo on the front', size: 'xx large', color: 'blue', price: 39.99},
        {product: "crew neck", description: 'A simple blue crewneck with Embroidered Logo on the front', size: 'xxx large', color: 'blue', price: 39.99},
        {product: "crew neck", description: 'A simple green crewneck with Embroidered Logo on the front', size: 'small', color: 'green', price: 39.99},
        {product: "crew neck", description: 'A simple green crewneck with Embroidered Logo on the front', size: 'medium', color: 'green', price: 39.99},
        {product: "crew neck", description: 'A simple green crewneck with Embroidered Logo on the front', size: 'large', color: 'green', price: 39.99},
        {product: "crew neck", description: 'A simple green crewneck with Embroidered Logo on the front', size: 'x large', color: 'green', price: 39.99},
        {product: "crew neck", description: 'A simple green crewneck with Embroidered Logo on the front', size: 'xx large', color: 'green', price: 39.99},
        {product: "crew neck", description: 'A simple green crewneck with Embroidered Logo on the front', size: 'xxx large', color: 'green', price: 39.99},
        {product: "crew neck", description: 'A simple pink crewneck with Embroidered Logo on the front', size: 'small', color: 'pink', price: 39.99},
        {product: "crew neck", description: 'A simple pink crewneck with Embroidered Logo on the front', size: 'medium', color: 'pink', price: 39.99},
        {product: "crew neck", description: 'A simple pink crewneck with Embroidered Logo on the front', size: 'large', color: 'pink', price: 39.99},
        {product: "crew neck", description: 'A simple pink crewneck with Embroidered Logo on the front', size: 'x large', color: 'pink', price: 39.99},
        {product: "crew neck", description: 'A simple pink crewneck with Embroidered Logo on the front', size: 'xx large', color: 'pink', price: 39.99},
        {product: "crew neck", description: 'A simple pink crewneck with Embroidered Logo on the front', size: 'xxx large', color: 'pink', price: 39.99},
        {product: "hoodies", description: 'Black hoodie to keep you warm and looking good all year long!', size: 'small', color: 'black', price: 59.99},
        {product: "hoodies", description: 'Black hoodie to keep you warm and looking good all year long!', size: 'medium', color: 'black', price: 59.99},
        {product: "hoodies", description: 'Black hoodie to keep you warm and looking good all year long!', size: 'large', color: 'black', price: 59.99},
        {product: "hoodies", description: 'Black hoodie to keep you warm and looking good all year long!', size: 'x large', color: 'black', price: 59.99},
        {product: "hoodies", description: 'Black hoodie to keep you warm and looking good all year long!', size: 'xx large', color: 'black', price: 59.99},
        {product: "hoodies", description: 'Black hoodie to keep you warm and looking good all year long!', size: 'xxx large', color: 'black', price: 59.99},
        {product: "hoodies", description: 'Pink hoodie to keep you warm and looking good all year long!', size: 'small', color: 'pink', price: 59.99},
        {product: "hoodies", description: 'Pink hoodie to keep you warm and looking good all year long!', size: 'medium', color: 'pink', price: 59.99},
        {product: "hoodies", description: 'Pink hoodie to keep you warm and looking good all year long!', size: 'large', color: 'pink', price: 59.99},
        {product: "hoodies", description: 'Pink hoodie to keep you warm and looking good all year long!', size: 'x large', color: 'pink', price: 59.99},
        {product: "hoodies", description: 'Pink hoodie to keep you warm and looking good all year long!', size: 'xx large', color: 'pink', price: 59.99},
        {product: "hoodies", description: 'Pink hoodie to keep you warm and looking good all year long!', size: 'xxx large', color: 'pink', price: 59.99},
        {product: "hoodies", description: 'Purple hoodie to keep you warm and looking good all year long!', size: 'small', color: 'pink', price: 59.99},
        {product: "hoodies", description: 'Purple hoodie to keep you warm and looking good all year long!', size: 'medium', color: 'pink', price: 59.99},
        {product: "hoodies", description: 'Purple hoodie to keep you warm and looking good all year long!', size: 'large', color: 'pink', price: 59.99},
        {product: "hoodies", description: 'Purple hoodie to keep you warm and looking good all year long!', size: 'x large', color: 'pink', price: 59.99},
        {product: "hoodies", description: 'Purple hoodie to keep you warm and looking good all year long!', size: 'xx large', color: 'pink', price: 59.99},
        {product: "hoodies", description: 'Purple hoodie to keep you warm and looking good all year long!', size: 'xxx large', color: 'pink', price: 59.99},
        {product: "sweat pants", description: 'Black sweatpants to keep you warm on those cold days!', size: 'small', color: 'black', price: 29.99},
        {product: "sweat pants", description: 'Black sweatpants to keep you warm on those cold days!', size: 'medium', color: 'black', price: 29.99},
        {product: "sweat pants", description: 'Black sweatpants to keep you warm on those cold days!', size: 'large', color: 'black', price: 29.99},
        {product: "sweat pants", description: 'Black sweatpants to keep you warm on those cold days!', size: 'x large', color: 'black', price: 29.99},
        {product: "sweat pants", description: 'Black sweatpants to keep you warm on those cold days!', size: 'xx large', color: 'black', price: 29.99},
        {product: "sweat pants", description: 'Black sweatpants to keep you warm on those cold days!', size: 'xxx large', color: 'black', price: 29.99},
        {product: "sweat pants", description: 'Blue sweatpants to keep you warm on those cold days!', size: 'small', color: 'blue', price: 29.99},
        {product: "sweat pants", description: 'Blue sweatpants to keep you warm on those cold days!', size: 'medium', color: 'blue', price: 29.99},
        {product: "sweat pants", description: 'Blue sweatpants to keep you warm on those cold days!', size: 'large', color: 'blue', price: 29.99},
        {product: "sweat pants", description: 'Blue sweatpants to keep you warm on those cold days!', size: 'x large', color: 'blue', price: 29.99},
        {product: "sweat pants", description: 'Blue sweatpants to keep you warm on those cold days!', size: 'xx large', color: 'blue', price: 29.99},
        {product: "sweat pants", description: 'Blue sweatpants to keep you warm on those cold days!', size: 'xxx large', color: 'blue', price: 29.99},

        

    ]
}